# Use Node v22.3.0 as the base image
FROM node:22.3.0

# Set the working directory inside the container
WORKDIR /app

# Copy essential files for installation
COPY .env package*.json vite.config.js ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port Vite will run on (e.g., 3002)
EXPOSE 3002

# Run the Vite development server
CMD ["npm", "run", "dev"]
